from crewai import Task
from agents import researcher, summarizer, fact_checker

# Task for the Researcher
research_task = Task(
    description=(
        "Conduct a comprehensive analysis of the latest advancements regarding {topic}. "
        "Identify key trends, breakthrough technologies, and potential industry impacts. "
        "Compile your findings into a detailed raw report."
    ),
    expected_output="A comprehensive raw report detailing the latest advancements and key trends on the topic.",
    agent=researcher,
)

# Task for the Summarizer
summarize_task = Task(
    description=(
        "Read the raw report generated by the researcher. "
        "Extract the most important points and synthesize them into a clear, structured summary. "
        "Ensure the summary is highly readable and logically organized."
    ),
    expected_output="A clear, structured summary of the core findings.",
    agent=summarizer,
)

# Task for the Fact-Checker
fact_check_task = Task(
    description=(
        "Review the summary generated by the synthesizer. "
        "Perform web searches to verify the key claims. "
        "Create the final report that includes the verified summary, flags any unverified claims, and lists citations (URLs) for the information."
    ),
    expected_output="A final markdown formatted report with the verified summary and a list of citations.",
    agent=fact_checker,
    output_file="final_research_report.md"
)
